services:
  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=Redis123.
volumes:
  redis-data:
    driver: local