services:
  redis:
    image: redis:alpine
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --bind 0.0.0.0
    restart: unless-stopped
volumes:
  redis-data:
    driver: local