services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack-server
    ports:
      - "6379:6379"     # Redis server port
      - "8001:8001"     # RedisInsight web UI port
    volumes:
      - redis-stack-data:/data
    environment:
      # Redis configuration
      REDIS_ARGS: "--appendonly yes --bind 0.0.0.0"
      # RedisInsight configuration (optional)
      REDISINSIGHT_HOST: "0.0.0.0"
      REDISINSIGHT_PORT: "8001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    ports:
      - "8002:8081"
    environment:
      REDIS_HOSTS: "redis-stack:redis-stack-server:6379"
      REDIS_HOST: "redis-stack-server"
      REDIS_PORT: "6379"
      HTTP_USER: "admin"
      HTTP_PASSWORD: "redis123"
    depends_on:
      redis-stack:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

volumes:
  redis-stack-data:
    driver: local

networks:
  app-network:
    driver: bridge
